# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "11:00"
      timezone: "Europe/Moscow"
    commit-message:
      prefix: "[github-actions] "
    rebase-strategy: "auto"
    milestone: 13
    open-pull-requests-limit: 3
    labels:
      - "C: Distribution"
      - "T: Maintenance"

  - package-ecosystem: "composer"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Moscow"
    commit-message:
      prefix: "[composer] "
    rebase-strategy: "auto"
    versioning-strategy: "lockfile-only"
    milestone: 13
    open-pull-requests-limit: 10
    labels:
      - "C: Backend"
      - "T: Maintenance"