version: "3.9"


services:
  # WebTLO для локальной разработки
  webtlo-dev:
    # Собираем локальный dev образ
    build:
      context: .
      target: dev
    container_name: webtlo-dev
    ports:
      # Порт для доступа к UI
      - "8090:80"
    volumes:
      # Проброшенный каталог с файлами конфигурации
      - ./webtlo-data-dev:/data
      # Проброшенный каталог WebTlo
      - ./src:/var/www/webtlo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Часовой пояс
      - TZ=Europe/Moscow
      # Выполняемые внутри контейнера фоновые задачи
      - WEBTLO_CRON=false
      # Стандартный пользователь внутри контейнера
      - WEBTLO_UID=1000
      - WEBTLO_GID=1000
    restart: on-failure
