[worker-status]
user = ${WEBTLO_UID}
group = ${WEBTLO_GID}
listen = 127.0.0.1:9002
pm = ondemand
pm.max_children = 1
pm.process_idle_timeout = 30s
pm.max_requests = 500
clear_env = no
php_flag[display_errors] = off
php_admin_flag[log_errors] = on
