name: Build release
run-name: Build on v${{ github.ref_name }} tag push  (${{ github.event.head_commit.message }})

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:

  validate:
    name: Check
    uses: ./.github/workflows/sub-check.yml

  docker:
    name: Build
    needs: [ validate ]
    uses: ./.github/workflows/sub-build-docker.yml
    with:
      REGISTRY_IMAGE: ${{ vars.REGISTRY_IMAGE || 'berkut174/webtlo' }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  zip:
    name: Build
    needs: [ validate ]
    uses: ./.github/workflows/sub-build-zip.yml

  make-release:
    name: Make release
    runs-on: ubuntu-latest
    needs: [ docker, zip ]
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - name: Restore release
        id: restore-release
        uses: actions/cache@v3
        with:
          key: ${{ github.ref_type }}-${{ github.sha }}-release
          path: ./release

      - uses: softprops/action-gh-release@v1
        name: Create release
        with:
          files: release/*.zip
          draft: true
          generate_release_notes: true