name: Sub. Check code style

on:
  workflow_call:

jobs:

  php-cs-fixer:
    name: code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: PhpCsFixer-${{ github.repository }}-${{ github.sha }}
          restore-keys: |
            PhpCsFixer-${{ github.repository }}-

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: -v --dry-run

  phpstan:
    name: code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: cd src && composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: Composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            Composer-${{ runner.os }}-

      - name: Install dependencies
        uses: MilesChou/composer-action/8.1@master
        with:
          args: install --working-dir=src --ignore-platform-reqs
        env:
          COMPOSER_CACHE_DIR: /tmp/composer-cache

      - name: PHPStan Static Analysis
        uses: MilesChou/composer-action/8.1@master
        with:
          args: src/vendor/bin/phpstan --memory-limit=512M