name: Sub. Build docker image

on:
  workflow_call:
    inputs:
      REGISTRY_IMAGE:
        required: true
        type: string
      WEBTLO_VERSION:
        type: string
        default: 'unknown'
      WEBTLO_SHA:
        type: string
        default: 'none'
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:

  build-docker:
    name: docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write version
        run: |
          cd src
          cat version.json \
            | jq --arg V ${{ inputs.WEBTLO_VERSION }} '.version=$V' \
            | jq --arg SH ${{ inputs.WEBTLO_SHA }} '.sha=$SH' \
            | jq '.installation="docker"' \
            > tmp.$$.json
          mv tmp.$$.json version.json

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.REGISTRY_IMAGE }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max